---
title: "11-7-19 tree"
author: "Megan Beaudry"
date: "11/7/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## R Markdown

# LOAD LIBRARIES
```{r}
library('forcats')
library('doParallel')
library('rpart')
library('rpart.plot')
library('mda')
library('ranger')
library('e1071')
library('gbm')
```


```{r}
clean_water_quality_data <- readRDS("../../data/processed_data/clean_water_quality_data.rds")
#if you get an error - this happens because you need to save the file first cause it refers to a relative path 
clean_data <- clean_water_quality_data
```


```{r}
set.seed(123)
trainset <- caret::createDataPartition(y = clean_data$A_butzleri_HSP60, p = 0.7, list = FALSE)
data_train = clean_data[trainset,] #extract observations/rows for training, assign to new variable
data_test = clean_data[-trainset,] #do the same for the test set
```



```{r}
n_cores <- 4 #number of cores to use
cl <- makePSOCKcluster(n_cores)
registerDoParallel(cl) #comment out this line if you don't want parallel computing
```


```{r}
set.seed(1111) #makes each code block reproducible
outcomename = "A_butzleri_HSP60"
Npred <- ncol(data_train)-1 # number of predictors
resultmat <- data.frame(Variable = names(data_train)[-1], Accuracy = rep(0,Npred)) #store performance for each variable
```

```{r}
fitControl <- trainControl(method="repeatedcv",number=5,repeats=5) 
fit1 = caret::train(A_butzleri_HSP60  ~ ., data=data_train, method="rpart",  trControl = fitControl, na.action = na.pass, tuneLength = 10) 
print(fit1$results)
```


```{r}
prp(fit1$finalModel, extra = 1, type = 1)
ww=17.8/2.54; wh=ww; #for saving plot
dev.print(device=png,width=ww,height=wh,units="in",res=600,file="../../results/rparttreearco.png") 
```




