---
title: "11-7-19 tree"
author: "Megan Beaudry"
date: "11/7/2019"
output: html_document
---
#all data is converted to yes or no. Method is being switched too RMSE. Rpart is being changed to lm 
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## R Markdown

# LOAD LIBRARIES
```{r}
library('forcats')
library('doParallel')
library('rpart')
library('rpart.plot')
library('mda')
library('ranger')
library('e1071')
library('gbm')
```


```{r}
clean_water_quality_data <- readRDS("../../data/processed_data/clean_water_quality_data.rds")
#if you get an error - this happens because you need to save the file first cause it refers to a relative path 
clean_data <- clean_water_quality_data
new_wq <- clean_data
```


```{r}
#want to convert a new column with acro as yes or no to get the percent of the samples positive 
#lets do arco first
new_wq <- new_wq %>% mutate(arco_y_n= 
                      ifelse(A_butzleri_HSP60 < "3.391993", "negative",
                      ifelse(A_butzleri_HSP60 > "3.391994", "positive",
                      "negative")))
#Now HF183 and the rest
new_wq <- new_wq %>% mutate(HF183= 
                      ifelse(HF183 < "3.329601", "negative",
                      ifelse(HF183 > "3.329602", "positive",
                      "negative")))
new_wq <- new_wq %>% mutate(HumM2= 
                      ifelse(HumM2 < "3.847449", "negative",
                      ifelse(HumM2 > "3.847450", "positive",
                      "negative")))
new_wq <- new_wq %>% mutate(CG01= 
                      ifelse(CG01 < "3.108565", "negative",
                      ifelse(CG01 > "3.108566", "positive",
                      "negative")))
new_wq <- new_wq %>% mutate(LeeSg= 
                      ifelse(LeeSg < "3.283979", "negative",
                      ifelse(LeeSg > "3.283980", "positive",
                      "negative")))
new_wq <- new_wq %>% mutate(Dog3= 
                      ifelse(Dog3 < "3.156549", "negative",
                      ifelse(Dog3 > "3.156550", "positive",
                      "negative")))
new_wq <- new_wq %>% mutate(MuBac= 
                      ifelse(MuBac < "3.554852", "negative",
                      ifelse(MuBac > "3.554853", "positive",
                      "negative")))
new_wq <- new_wq %>% mutate(Rum2Bac= 
                      ifelse(Rum2Bac < "3.457125", "negative",
                      ifelse(Rum2Bac > "3.457126", "positive",
                      "negative")))
new_wq <- new_wq %>% mutate(Salmonella_spp_InvA= 
                      ifelse(Salmonella_spp_InvA < "3.170848", "negative",
                      ifelse(Salmonella_spp_InvA > "3.170849", "positive",
                      "negative")))
new_wq <- new_wq %>% mutate(Campylobacter_spp_Van_Dkye= 
                      ifelse(Campylobacter_spp_Van_Dkye < "3.554852", "negative",
                      ifelse(Campylobacter_spp_Van_Dkye > "3.554853", "positive",
                      "negative")))

#water quality indicators
new_wq <- new_wq %>% mutate(Enterococcus_CCE= 
                      ifelse(Enterococcus_CCE < "3.102", "negative",
                      ifelse(Enterococcus_CCE > "3.103", "positive",
                      "negative")))

new_wq <- new_wq %>% mutate(thermotolerant_coiforms= 
                      ifelse(thermotolerant_coliforms < "2.602", "negative",
                      ifelse(thermotolerant_coliforms > "2.603", "positive",
                      "negative")))
clean_data_1 <- new_wq
clean_data_1 <- new_wq
```



```{r}
clean_data_2 <- clean_data_1[, c(25,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24)]
clean_data_2 <- clean_data_2 %>% dplyr::select(-A_butzleri_HSP60)
```


```{r}
set.seed(123)
trainset <- caret::createDataPartition(y = clean_data_2$arco_y_n, p = 0.7, list = FALSE)
data_train = clean_data_2[trainset,] #extract observations/rows for training, assign to new variable
data_test = clean_data_2[-trainset,] #do the same for the test set
```



```{r}
n_cores <- 4 #number of cores to use
cl <- makePSOCKcluster(n_cores)
registerDoParallel(cl) #comment out this line if you don't want parallel computing
```

```{r}
#There is probably a nicer tidyverse way of doing this. I just couldn't think of it, so did it this way.
set.seed(1111) #makes each code block reproducible
outcomename = "arco_y_n"
fitControl <- trainControl(method="repeatedcv",number=5,repeats=5) #setting CV method for caret
Npred <- ncol(data_train)-1 # number of predictors
resultmat <- data.frame(Variable = names(data_train)[-1], ACC = rep(0,Npred)) #store performance for each variable
for (n in 2:ncol(data_train)) #loop over each predictor. For this to work, outcome must be in 1st column
{
  fit1 <- caret::train( as.formula(paste(outcomename, "~",names(data_train)[n])) , data = data_train, method = "rpart", trControl = fitControl, na.action = na.pass, tuneLength = 20)
resultmat[n-1,2]= max(fit1$results$Accuracy)  
}
print(resultmat)

#In order to get this code to work i had to specify the carett:: package
```


```{r Julias}
##outcomename = "arco_y_n"
#Npred <- ncol(data_train)-1 # number of predictors
#resultmat <- data.frame(Variable = names(data_train)[-1], Accuracy = rep(0,Npred)) #store performance for each variable
```

```{r}
fitControl <- trainControl(method="repeatedcv",number=5,repeats=5) 
fit1 = caret::train(arco_y_n  ~ ., data=data_train, method="rpart",  trControl = fitControl, na.action = na.pass, tuneLength = 100) 
print(fit1$results)
```


```{r}
prp(fit1$finalModel, extra = 1, type = 1)
ww=17.8/2.54; wh=ww; #for saving plot
dev.print(device=png,width=ww,height=wh,units="in",res=600,file="../../results/rparttreearco_j_all_P_N.png") 
```




