---
title: "11-7-19 tree"
author: "Megan Beaudry"
date: "11/7/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## R Markdown
Arco is the only yes no variable. Tune length is increased to 50. 
# LOAD LIBRARIES
```{r}
library('tidyr')
library('dplyr')
library('forcats')
library('ggplot2')
library('knitr')
library('caret')
library('doParallel')
library('rpart')
library('rpart.plot')
library('mda')
library('ranger')
library('e1071')
library('visdat')
```


# LOAD DATA
```{r}
clean_water_quality_data <- readRDS("../../data/processed_data/clean_water_quality_data.rds")
#if you get an error - this happens because you need to save the file first cause it refers to a relative path 
clean_data <- clean_water_quality_data
```




# ORGANIZE DATA

Let's turn all variables into yes or no, and see if we can predict A. butzleri.
```{r}
#lets make a new object in case we mess something up
new_wq <- clean_water_quality_data


#convert characters to categorical varaibles
new_wq$Pond <- as.factor(as.character(new_wq$Pond))
new_wq$Sampling_Site <- as.factor(as.character(new_wq$Sampling_Site))
new_wq$Sampling_Site <- as.factor(as.character(new_wq$Sampling_Site))
str(new_wq)

#want to convert a new column with acro as yes or no to get the percent of the samples positive 
#lets do arco first
new_wq <- new_wq %>% mutate(arco_y_n= 
                      ifelse(A_butzleri_HSP60 < "3.391993", "no",
                      ifelse(A_butzleri_HSP60 > "3.391994", "yes",
                      "no")))
#Now HF183 and the rest
#new_wq <- new_wq %>% mutate(HF183_y_n= 
                     # ifelse(HF183_new < "3.329601", "no",
                     # ifelse(HF183_new > "3.329602", "yes",
                      #"no")))
#new_wq <- new_wq %>% mutate(HumM2_y_n= 
                      #ifelse(HumM2 < "3.847449", "no",
                      #ifelse(HumM2 > "3.847450", "yes",
                      #"no")))
#new_wq <- new_wq %>% mutate(CG01_y_n= 
                      #ifelse(CG01 < "3.108565", "no",
                      #ifelse(CG01 > "3.108566", "yes",
                      #"no")))
#new_wq <- new_wq %>% mutate(LeeSg_y_n= 
                      #ifelse(LeeSg < "3.283979", "no",
                      #ifelse(LeeSg > "3.283980", "yes",
                      #"no")))
#new_wq <- new_wq %>% mutate(Dog3_y_n= 
                     # ifelse(Dog3 < "3.156549", "no",
                     # ifelse(Dog3 > "3.156550", "yes",
                     ## "no")))
#new_wq <- new_wq %>% mutate(MuBac_y_n= 
                      #ifelse(MuBac < "3.554852", "no",
                     # ifelse(MuBac > "3.554853", "yes",
                      #"no")))
#new_wq <- new_wq %>% mutate(Rum2Bac_y_n= 
                     # ifelse(Rum2Bac < "3.457125", "no",
                     # ifelse(Rum2Bac > "3.457126", "yes",
                     # "no")))
#new_wq <- new_wq %>% mutate(Salmonella_y_n= 
                     # ifelse(Salmonella_spp_InvA < "3.170848", "no",
                     # ifelse(Salmonella_spp_InvA > "3.170849", "yes",
                     # "no")))
#new_wq <- new_wq %>% mutate(Campy_y_n= 
                      #ifelse(Campylobacter_spp_Van_Dkye < "3.554852", "no",
                      #ifelse(Campylobacter_spp_Van_Dkye > "3.554853", "yes",
                      #"no")))

#water quality indicators
#new_wq <- new_wq %>% mutate(Entero_y_n= 
                     # ifelse(Enterococcus_CCE < "3.102", "no",
                     # ifelse(Enterococcus_CCE > "3.103", "yes",
                     # "no")))

#new_wq <- new_wq %>% mutate(thermo_y_n= 
                     # ifelse(thermotolerant_coliforms < "2.602", "no",
                     # ifelse(thermotolerant_coliforms > "2.603", "yes",
                     # "no")))
clean_data_1 <- new_wq

```


MOVE
Move the outcome variable to the first row
```{r reorder}
#move A. butzleri to first row
clean_data_2 <- clean_data_1[, c(25, 1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24)]
clean_data_2 <- clean_data_2 %>% dplyr::select(-A_butzleri_HSP60)
```

REMOVE

```{r}
#clean_data_2 <- clean_data_2 %>% dplyr::select(-HF183, -HumM2, -LeeSg, -CG01, -Dog3, -Rum2Bac, -A_butzleri_HSP60, -Salmonella_spp_InvA, -Campylobacter_spp_Van_Dkye, -Enterococcus_CCE, -total_coliforms, -E_coli, -Enteroalert, -Sampling_Site, -Pond, -Date, -Date_Sampled, -Week, -Rainfall, -arco_new, -MuBac, -Sample_ID, -HF183_new, -Shigatoxin_1, -Shigatoxin_2, -thermotolerant_coliforms)
```



SPLIT data
```{r split data}

library(caret)
library("tidyverse")
#this code does the data splitting. I still assume that your data is stored in the `d` object.
#uncomment to run
set.seed(123)
#extract observations/rows for training, assign to new variable. 
#Extracts 70% of the data into the trainset
trainset <- caret::createDataPartition(y = clean_data_2$arco_y_n, p = 0.7, list = FALSE)
#subsets out the dataset
data_train = clean_data_2[trainset,] 
#do the same for the test set
data_test = clean_data_2[-trainset,] 
```



```{r}
mlr::measureACC("yes", data_train$arco_y_n)
```

```{r}
##data_train_2 <- data_train %>% dplyr::select(-HF183, -HumM2, -LeeSg, -CG01, -Dog3, -Rum2Bac, -A_butzleri_HSP60, -Salmonella_spp_InvA, -Campylobacter_spp_Van_Dkye, -Enterococcus_CCE, -total_coliforms, -E_coli, -Enteroalert, -Sampling_Site, -Pond, -Date, -Date_Sampled, -Week, -Rainfall)
```



```{r}


#There is probably a nicer tidyverse way of doing this. I just couldn't think of it, so did it this way.
set.seed(1111) #makes each code block reproducible
outcomename = "arco_y_n"
fitControl <- trainControl(method="repeatedcv",number=5,repeats=5) #setting CV method for caret
Npred <- ncol(data_train)-1 # number of predictors
resultmat <- data.frame(Variable = names(data_train)[-1], RMSE = rep(0,Npred)) #store performance for each variable
for (n in 2:ncol(data_train)) #loop over each predictor. For this to work, outcome must be in 1st column
{
  fit1 <- caret::train( as.formula(paste(outcomename, "~",names(data_train)[n])) , data = data_train, method = "rpart", trControl = fitControl, na.action = na.pass, tuneLength = 50)
resultmat[n-1,2]= max(fit1$results$Accuracy)  
}
print(resultmat)

#In order to get this code to work i had to specify the carett:: package
```

#want accuracy to be around .7
```{r Arco}
set.seed(1111)
fitControl <- trainControl(method="repeatedcv",number=5,repeats=5) 
fit2 = caret::train(arco_y_n  ~ ., data=data_train, method="rpart",  trControl = fitControl, na.action = na.pass, tuneLength = 20) 
print(fit2$results)
```

```{r}
arco_tree <- prp(fit2$finalModel, extra = 1, type = 1)
ww=17.8/2.54; wh=ww;
dev.print(device=png,width=ww,height=wh,units="in",res=600,file="../../results/arco_tree_2.png")
```