# Overview

Title of project: "Bacterial Sources of Pollution in Urban Stormwater Impacted Bodies of Water"

Author of project: Megan Beaudry


# Instructions

Write your comments and feedback below for each section/compontent of the project. The goal should be to help the author improve their project. Make comments as constructive and actionable as possible. You can provide both criticism and praise.

For each component, pick one summary statement by deleting the ones that do not apply and keeping only the one that you think most closely summarizes a given component. 

Delete any sections/text of this template that are not part of your final review document.


# Specific project content evaluation
Evaluate the different parts of the project by filling in the sections below.


## Background, Context and Motivation
How well is the context of the project described? Is a comprehensive background, including summary of previous/related work given? Is the project well placed into the context of existing work (including proper referencing of existing work). Is it clear why the project was undertaken and what new information it hopes to provide?

### Feedback and Comments

The context of the project is described with enough detail to understand what you are doing. There is a good deal of fundamental information to introduce one to the science at hand, with good references as well as background information and why the project is important as a whole. It was really well written and informative!

### Summary assessment
* strong contextualization and motivation


## Question description
How well and clear are the question(s)/hypotheses the project aims to address described? Is it clear how the questions relate to the data?


### Feedback and Comments

The questions are described well and do relate to the study at hand. The questions are not reaching too far, but instead achievable and interesting. 

### Summary assessment
* question/hypotheses fully clear


## Data description
How well is the data overall described? Is the source provided? Is a codebook or other meta-information available that makes it clear what the data is? 

### Feedback and Comments

The source of the data is given as well as clearly described. I did not see a codebook, necessarily, but the code and data is readily available. 

### Summary assessment
* source and overall structure of data well explained


## Data wrangling and exploratory analysis
How well is the data cleaned/processed and explored? Are all steps reasonable and well explained? Are alternatives discussed and considered? Are meaningful exploratory results shown (e.g. in the supplementary materials)?

### Feedback and Comments

The data was well explored and "wrangled". Everything is reasonably explained. You did a nice job on walking through the cleaning process. There are a few alternatives discussed, and very good supplementary materials. 

### Summary assessment
* essentially no weaknesses in wrangling and exploratory component



## Appropriateness of Analysis
Were the analysis methods appropriate for the data? Was the analysis done properly? Were different components of the analysis (e.g. performance measure, variable selection, data pre-processing, model evaluation) done in the best way possible and explained well?

### Feedback and Comments

I thought the analysis was very appropriate for the data and also done properly. While there could have been other ways to do it, I am not familiar with all of the methods that would work for this, but what you did worked just fine. I did not see any issues in how it was done, and it was well thought out. 

### Summary assessment
* strong and reasonable analysis

## Presentation
How well are results presented? Are tables and figures easy to read and understand? Are the main figures/tables publication level quality? 

### Feedback and Comments

The figures and results are easy to understand. I enjoyed the figures a lot! I would say they are publication level quality, if not maybe just below publication level. You did a great job here. 

### Summary assessment
* results are very well presented


## Discussion/Conclusions
Are the study findings properly discussed? Are strengths and limitations acknowledged? Are findings interpreted properly?

### Feedback and Comments

The findings are interpretated well, as are the strengths/limitations. I thought you did an excellent job explaining the findings. Nice work. 

### Summary assessment
* strong, complete and clear discussion


## Further comments

_Add any other comments regarding the different aspects of the project here. Write anything you think can help your classmate improve their project._



# Overall project content evaluation
Evaluate overall features of the project  by filling in the sections below.


## Structure
Is the project well structured? Are files in well labeled folders? Do files have reasonable names? Are all "junk" files not needed for analysis/reproduction removed? By just looking at files and folders, can you get an idea of how things fit together?

### Feedback and Comments

Overall, the project is well structured. Everything is organized perfectly, and it is easy to reassemble. Very nice work Megan!

### Summary assessment
* well structured


## Documentation 
How well is the project documented? Are you able to understand each step of the whole analysis, each decision that was made, and each line of code? Is enough information provided as comments in code or as part of Rmd files? 

### Feedback and Comments

The project is well documented. While I suppose some of the little details were left out in the actual code, you had good reasoning in the Manuscript to explain why you did what you did, which actually was very helpful while reviewing, but also to me, as a novice model maker, to see what works best. Great job!

### Summary assessment
* fully and well documented



## Reproducibility
Are all results fully reproducible? Is documentation provided which clearly explains how to reproduce things, and does it work without the need for any manual intervention?

### Feedback and Comments

Everything is reproducible. As far as I could tell while running the code, I did not see any need for manual intervention. 


### Summary assessment
* fully reproducible without issues


## Thoroughness
How thorough was the overall study? Were alternatives (e.g. different ways of processing the data or different models) considered? Were alternatives discussed? Were the questions/hypotheses fully and thoroughly addressed?

### Feedback and Comments

Overall, the project was well thought out. I don't believe you missed any critical questions you wanted to answer in your analysis.

### Summary assessment
* strong level of thorougness


## Further comments

Overall I think you did an excellent job. This is a great example of a Data Analysis Project! Good job Megan!




